### PR TITLE
Fix PHP Notice "Only variables ... by reference" in DefaultAssocLangModel.php on line 70

### PR DESCRIPTION
**Pull request by richard67**
Fix PHP Notice "Only variables should be passed by reference" in /administrator/components/com_associations/Model/DefaultAssocLangModel.php on line 70

### CODE REVIEW

**Comment by richard67** [comment]
Saving the changed child article works now with this fix.

**Comment by richard67** [comment]
P.S.: And the icon for that language of that child article changes from brown to green after change. So it seems we are on a good way :smile:

**Comment by lavipr** [comment]
Thanks a lot :)

**Comment by richard67** [comment]
But now finally good night :)

**Comment by lavipr** [comment]
:D Good night.

**Pull request merged**
