### PR TITLE
4.0 dev pr 25403 fix php notices 2

### PR DESCRIPTION
**Pull request by richard67**
See title.

### CODE REVIEW

**Comment by richard67** [comment]
I've just tested, it works. Blog sample data installation finishs now with success.

Other question: Why don't you come to the JoomlaDay? No time? Or no mood? Or you would really like to go there, but the tickets are too expensive? If the latter: I could help. I could invite you as a kind of thank you for your work and a kind of motivation for going on with contributing to our project. You know I was gifted with tickets in the same way, but have a good job so could also pay my tickets, and so I could help some poor student maybe. If I can help just use the contact form on my web site.

P.S.: You can use German language then.

**Comment by lavipr** [comment]
thank you :)

I'm gonna reconsider JoomlaDay. This time there is a student ticket. The price is not the problem. But thank you very much for the offer! I can't really plan the month yet, so I said no for now.

**Comment by richard67** [comment]
Would be nice to meet you there and talk a bit.

You know, I am a JBS (Joomla Bug Squad) member since a while, but am a normal volunteer contributor like you are. We have a lack of helpers so I would really like to know what we could do better to attract volunteers. I think sometimes things on GitHub can be a bit discouraging.

**Comment by lavipr** [comment]
In fact, a conversation would be interesting. And I have already noticed the problem with too few helpers.

For me personally it is very helpful that someone looks again at what I have done, and at best can show what and how something can be improved so that I can learn from it :)

**Comment by richard67** [comment]
Well, you are doing a good job. There are less than 1 % of all PR's which are accepted as they are, without any review or correction, I would say. And you are already familiar with checking the PHPCS logs of Drone, with GitHub and so on. And your PR is not a small one, so I would say all is ok like it works now.

Just let me know when you want to solve a problem yourself because you want to learn, then I will wait with helping.

You know, I think Joomla stuff should be a hobby if you don't have any commercial business with it, and as a hobby it should be fun.

So I never would force anyone to join the JBS if that would not be fun for that person or too time consuming or not the right focus. There are also other teams people can help. E.g. also the automated testing team needs people, too.

And it does not even need to be in any team. If you say you will help from time to time with testing other people's PRs if you have some interest in it, or continue contributing from time to time, or find the one or other bug, that would be nice, too.

**Pull request merged**
